# Site settings
title: Unpacker JS
about: Unpack or deobfuscate JavaScript Online Tool. Algorithm by Matthewfl.  
email: your-email@domain.com
url: https://example.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
created: 2015/02/18

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3C4D5F #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
# Nav-menu
nav:
  - title: user
    url: http://salipropham.github.io
  - title: github
    url: http://twitter.com/jekyllrb
  - title: download
    url: http://twitter.com/jekyllrb


# Footer settings
footer:
  copyright: SaliproPhạm
  left: About
  right: Location
  credits: Credits

# Postal address (add as many lines as necessary)
left:
    text: 3481 Melrose Place


# Build settings
markdown: kramdown
permalink: pretty
